#!/usr/bin/env bash
# Install nginx on your web-01 server

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo /etc/init.d/nginx restart
sudo rm /var/www/html/*.html
echo "Hello World!" | sudo tee /var/www/html/index.html
