#!/usr/bin/env bash
# This Script redirects

target="^\tlocation / {"
replacement="\tlocation /redirect_me {\n\t\treturn 301 \@scheme://youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo rm /var/www/html/*.html
echo "Hello World" | sudo tee /var/www/html/index.html
sudo sed -i "s|$target|$replacement|" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
